### ISSUE TITLE
How to add sample widget on wp dashboard?

### ISSUE THREAD

**Issue by MehtaRiddhi** [MehtaRiddhi/wp-library#3]
Add a sample widget with a different option on wp dashboard.

Add below setting option in the widget.

# Task

- [ ] Text box & Text area
- [ ] Drop down 
- [ ] Check boxes
- [ ] Radio button
- [ ] Multi select drop down box
- [ ] File/Image uplode
- [ ] Ranger
- [ ] Date & Color picker
