### ISSUE TITLE
How to Add Custom Widget in plugine?

### ISSUE THREAD

**Issue by MehtaRiddhi** [MehtaRiddhi/wp-library#8]
Add a sample widget with a different option in a plugin.

Add below setting option in the widget.

# Task
- [ ] text box , text area
- [ ] drop down 
- [ ] check boxes
- [ ] radio button
- [ ] Multi select drop down box
- [ ] File/Image uplode
- [ ] Ranger
- [ ] Date & Color picker
